/// <mls fileReference="_102021_/l2/agentMaterializeL1/steps/tests60/render.ts" enhancement="_blank"/>

// The monitor test file of one page (skills/monitorTests.md, `PageTestsFile`): data only, no import, nothing
// runs when it loads. Rendered by code from the gated cases; the model never writes the file.

import type { M12TestCase } from '/_102021_/l2/agentMaterializeL1/helpers/m12Gates.js';
import { fileRef, type M12FileInfo } from '/_102021_/l2/agentMaterializeL1/helpers/m12Names.js';

/** Keeps only the keys the monitor reads, in a stable order. Throws on a shape the gate cannot read. */
export function normalizeTestCases(value: unknown): M12TestCase[] {
  if (!Array.isArray(value)) throw new Error('cases must be an array.');
  return value.map((raw, index) => {
    if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error(`case ${index} must be an object.`);
    const item = raw as Record<string, unknown>;
    const expect = (item.expect && typeof item.expect === 'object' ? item.expect : {}) as Record<string, unknown>;
    if (typeof expect.ok !== 'boolean') throw new Error(`case ${index}: expect.ok must be a boolean.`);
    const params = item.params && typeof item.params === 'object' && !Array.isArray(item.params) ? item.params as Record<string, unknown> : {};
    const refs = item.paramFieldRefs && typeof item.paramFieldRefs === 'object' && !Array.isArray(item.paramFieldRefs)
      ? Object.fromEntries(Object.entries(item.paramFieldRefs as Record<string, unknown>).filter(([, ref]) => typeof ref === 'string')) as Record<string, string>
      : undefined;
    const shape = expect.shape === 'object' || expect.shape === 'array' || expect.shape === 'paginated' ? expect.shape : undefined;
    return {
      id: String(item.id ?? ''),
      routine: String(item.routine ?? ''),
      params,
      ...(refs && Object.keys(refs).length ? { paramFieldRefs: refs } : {}),
      expect: {
        ok: expect.ok,
        ...(typeof expect.errorCode === 'string' && expect.errorCode ? { errorCode: expect.errorCode } : {}),
        ...(typeof expect.minItems === 'number' ? { minItems: expect.minItems } : {}),
        ...(shape ? { shape } : {}),
        ...(typeof expect.itemsKey === 'string' && expect.itemsKey ? { itemsKey: expect.itemsKey } : {}),
      },
      mutating: item.mutating === true,
    };
  });
}

/**
 * Read cases first (the monitor runs every read of every file before the rest, in declaration order); inside
 * the rest, declaration order is kept, so a create -> update -> read-back sequence stays as proposed.
 */
export function orderCases(cases: readonly M12TestCase[]): M12TestCase[] {
  const read = cases.filter(item => item.expect.ok && !item.mutating);
  return [...read, ...cases.filter(item => !(item.expect.ok && !item.mutating))];
}

export function renderPageTests(input: { file: M12FileInfo; moduleName: string; pageId: string; actor: string; cases: readonly M12TestCase[] }): string {
  const data = {
    moduleName: input.moduleName,
    page: input.pageId,
    variant: 'backend',
    ...(input.actor ? { actor: input.actor } : {}),
    cases: orderCases(input.cases),
  };
  return [
    `/// <mls fileReference="${fileRef(input.file)}" enhancement="_blank"/>`,
    '',
    '// Monitor cases of this page backend, as data (skills/monitorTests.md). Generated by agentMaterializeL1.',
    `export const pageTests = ${JSON.stringify(data, null, 2)} as const;`,
    '',
  ].join('\n');
}
